config/routes.rb
Rails.application.routes.draw do
 
  resources :tableros
  patch 'grupos/agregarusuario', to: 'grupos#agregarusuario'
  put 'grupos/agregarusuario', to: 'grupos#agregarusuario'
  
  resources :grupos do
    resources :posts
  end

  devise_for :usuarios
  get 'misions/mismisiones'

  get 'estrellas/nueva' #Habilitar sólo para pruebas
  post 'estrellas', to: 'estrellas#crear'
  post 'autoes', to: 'estrellas#crearauto'

  get 'usuarios', to: 'usuarios#index'
  get 'usuarios/:idusuario', to: 'usuarios#mostrar', as:'veruser'
  
  patch 'usuarios/darestrellas', to: 'estrellas#darestrellas'
  put 'usuarios/darestrellas', to: 'estrellas#darestrellas'
  




  resources :misions do
  	resources :objetivos
  	member do
  		put "like", to: "misions#upvote"
  		put "dislike", to: "misions#downvote"
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'root#index'
end

app/models/mision.rb
class Mision < ApplicationRecord
	acts_as_votable
	has_many :objetivos
	#Paperclip
	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/misions_controller.rb
class MisionsController < ApplicationController
  before_action :set_mision, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :validarusuario
  before_action :validaradmin, except: [:show, :index, :upvote, :downvote, :mismisiones]


  # GET /misions
  # GET /misions.json
  def index
      @misions = Mision.all

  end

  def mismisiones
      #misiones que sólo coincidan con el voter_id del current_usuario
      @misions = current_usuario.find_liked_items

  end
  # GET /misions/1
  # GET /misions/1.json
 def show
     @objetivos = Objetivo.select("id", "nombre","descripcion").where(:mision_id => params[:id])
     @estrellas = Estrella.select("idobjetivo_id", "idusuario_id", "est1", "est2", "est3").where(idusuario_id: current_usuario.id)
     #Para optimizar se deberá agregar un campo de idmision y requerirlo en la misma consulta de la línea anterior, para disminuir el tamaño del array
  end

  # GET /misions/new
  def new
    @mision = Mision.new
  end

  # GET /misions/1/edit
  def edit
  end

  def upvote
    @mision.upvote_by current_usuario
    redirect_to :back
  end

  def downvote
    @mision.downvote_by current_usuario
    redirect_to :back
  end

 
  # POST /misions
  # POST /misions.json
  def create
    @mision = Mision.new(mision_params)

    respond_to do |format|
      if @mision.save
        format.html { redirect_to @mision, notice: 'La misión se creó correctamente.' }
        format.json { render :show, status: :created, location: @mision }
      else
        format.html { render :new }
        format.json { render json: @mision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /misions/1
  # PATCH/PUT /misions/1.json
  def update
    respond_to do |format|
      if @mision.update(mision_params)
        format.html { redirect_to @mision, notice: 'La misión se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @mision }
      else
        format.html { render :edit }
        format.json { render json: @mision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /misions/1
  # DELETE /misions/1.json
  def destroy
    @mision.destroy
    respond_to do |format|
      format.html { redirect_to misions_url, notice: 'La misión se eliminó correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mision
      @mision = Mision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mision_params
      params.require(:mision).permit(:nombre, :nivel, :descripcion, :urltemario, :urlimagen, :comentario, :habilitado, :visible, :image)
    end
    def validarusuario
      unless usuario_signed_in?
        redirect_to new_usuario_session_path, notice: "Hay que iniciar sesión para acceder a esta sección."
      end
    end 
    def validaradmin
      unless current_usuario.es_admin?
        redirect_to misions_path, notice: "No disponés de permisos suficientes para acceder a esta sección."
      end
    end
end

app/views/misions/_form.html.erb
<%= form_for mision, html: { multipart: true } do |f| %>
  <% if mision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mision.errors.count, "error") %> prohibited this mision from being saved:</h2>

      <ul>
      <% mision.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="input-group">
   <span class="input-group-addon">Nombre de la misión</span>
    <%= f.text_field :nombre , :class => "form-control " %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">Nivel</span>
    <%= f.text_field :nivel, :class => "form-control "  %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">Imagen</span>
    <%= f.file_field :image, :class => "form-control "  %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">Descripción</span>
    <%= f.text_area :descripcion, :class => "form-control "  %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">URL del temario</span>
    <%= f.text_field :urltemario, :class => "form-control "  %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">URL de la imagen</span>
    <%= f.text_field :urlimagen, :class => "form-control "  %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">Comentarios</span>
    <%= f.text_field :comentario , :class => "form-control " %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">¿Misión habilitada?</span>
    <%= f.check_box :habilitado, :class => "form-control "  %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">¿Misión visible?</span>
    <%= f.check_box :visible, :class => "form-control "  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/misions/edit.html.erb
<h1>Editando la Misión</h1>

<%= render 'form', mision: @mision %>

<%= link_to '¡Dar un vistazo!', @mision %> |
<%= link_to 'Volver atrás', misions_path %>

app/views/misions/index.html.erb
<h1>¡Hay misiones que cumplir!</h1>

<div class="transitions-enabled clearfix masonry" >

<% if current_usuario.es_docente? %>
    <div class="box col1 masonry-brick">
    <div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Crear nueva misión</h2>
    </div>
   <div class="panel-body">
    <%= link_to '+', new_mision_path, :class =>"btn btn-success" %>
   </div>
   </div></div>

<% end %>




    <% @misions.each do |mision| %>
<div class="box col3 masonry-brick">
    <div class="panel panel-default"> <!-- Agregar distinción de col* según cantidad de visitas -->
    <div class="panel-heading">
        <h2 class="panel-title"><%= mision.nombre %></h2>
    </div>
    <div class="panel-body">
<%= image_tag mision.image.url(:large), :class => "img-rounded"%><br>
<small>Nivel: <i><%= mision.nivel %></i></small>
<p><%= mision.descripcion %></p>
<%= link_to "Dar un vistazo", mision.urltemario, :class => "btn btn-default" %> <%= link_to "¡Comenzar misión!", mision, :class => "btn btn-default"  %>


<% if current_usuario.es_docente? %>

  <%= link_to "Editar", edit_mision_path(mision), :class => "btn btn-warning"  %>
  <%= link_to "Eliminar", mision, method: :delete, data: { confirm: "¿Estás seguro que deseás eliminar esta misión?" }, class: "btn btn-danger"  %>

<% end %>




    </div>
    </div>
</div>

      <!--- FALTA VERIFICAR SI ESTÁ HABILITADA Y VISIBLE
        <td><%= mision.comentario %></td>
        <td><%= mision.habilitado %></td>
        <td><%= mision.visible %></td>

        -->
    <% end %>


</div>
<br>

app/views/misions/mismisiones.html.erb
<h1>¡Estas son tus misiones!</h1>

<div class="transitions-enabled clearfix masonry" >

    <% @current_usuario.find_liked_items.each do |mision| %>



<div class="box col3 masonry-brick">
    <div class="panel panel-default"> <!-- Agregar distinción de col* según cantidad de visitas -->
    <div class="panel-heading">
        <h2 class="panel-title"><%= mision.nombre %></h2>
    </div>
    <div class="panel-body">
<%= image_tag mision.image.url(:large), :class => "img-rounded"%><br>
<small>Nivel: <i><%= mision.nivel %></i></small>
<p><%= mision.descripcion %></p>
 <%= link_to "¡Entrar a la misión!", mision, :class => "btn btn-primary" %>
    </div>
    </div>
</div>


    <% end %>

app/views/misions/new.html.erb
<h1>Crear nueva Misión</h1>

<%= render 'form', mision: @mision %>

<%= link_to 'Volver atrás', misions_path %>

app/views/misions/show.html.erb
<div class="container-fluid">
<%= link_to content_tag(:span, " ", class:"fa fa-fa-hand-o-left-2x"), misions_path %>
  <div class="row">
      <div class="col-xs-12 col-sm-9">

      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><%= @mision.nombre %></h2>


        </div>

      <div class="panel-body"><div class="row pull-right">
          <% if current_usuario.liked? @mision %>


<%= link_to dislike_mision_path(@mision), method: :put, class: "btn btn-warning"  do %>
<%= content_tag(:span, " Quitar de Mis Misiones ", class: "fa fa-trash-o") %>
</span>

<% end %>
<% else %>
<%= link_to like_mision_path(@mision), method: :put, class: "btn btn-success" do %>
<%= content_tag(:span, " Agregar a Mis Misiones", class: "fa fa-plus") %>

<% end %>
<% end %>

<span class="label label-default" data-toggle="tooltip" title="Cantidad de personas que siguen esta misión"><%= @mision.get_upvotes.size %>
  </span>
</div>
        <small><%= @mision.nivel %></small>
        <p><%= @mision.descripcion %></p>
        <small><%= @mision.comentario %></small>
          <%= link_to "Ver temario", @mision.urltemario %>
      </div>
      </div>
      </div>

      <div class="col-xs-12 col-sm-3"><%= image_tag @mision.image.url(:large), :class => "img-thumbnail" %></div>
      </div>

  </div><!--- Características de la misión -->




<div class="panel panel-default">
<div class="panel-heading">
Objetivos
</div>
<div class="panel-body">
<% nest1=0 %>
<% nest2=0 %>
<% nest3=0 %>
      <% @objetivos.each do |objetivo| %>
                       

      <% estre1 = false %>
      <% estre2 =false %>
      <% estre3= false %>
      <div class="row">
          <% if current_usuario.es_docente? %>

        <div class="col-md-2"><span data-toggle="tooltip" title="Editar misión"><%= link_to content_tag(:i, "", class: "fa fa-pencil"), edit_mision_objetivo_path(@mision.id, objetivo.id), :class => "btn btn-warning" %></span>

        <span data-toggle="tooltip" title="Eliminar misión">
        <%= link_to content_tag(:i, " ", class: "fa fa-trash"), mision_objetivo_path(@mision.id, objetivo.id), method: :delete, data: { confirm: "¿Estás seguro que deseás eliminar esta misión?" }, class: "btn btn-danger"  %></span></div>

             <% end %>
        <div class="col-xs-7 col-md-8"><strong><%= link_to objetivo.nombre, mision_objetivo_path(mision_id: @mision.id, id: objetivo.id) %></strong><p><%= objetivo.descripcion %></p></div>
        
        <div class="col-xs-5 col-md-2 pull-right">
  <% existe = false; #variable que comprobará si existe el objetivo%>
     <% @estrellas.each do |r| %>
  <% if r.idobjetivo_id==objetivo.id %>
    <% existe = true; #el objetivo existe! %>
    <% if r.est1? %>
      <i class="fa fa-star fa-2x" aria-hidden="true"></i>
      <% nest1=nest1+1 %>
      <% if r.est2? %>
        <i class="fa fa-star fa-2x" aria-hidden="true"></i>
        <% nest2=nest2+1 %>
        <% if r.est3? %>
        <i class="fa fa-star fa-2x" aria-hidden="true"></i>
        <% nest3=nest3+1 %>
      <% else %>
        <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
        <% end %>
      <% else %>
        <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
        <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
      <% end %>
    <% else %>
      <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
      <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
      <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
    <% end %>
    
<% end %>

<% end %>

<% if existe==false %>
        <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
      <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
      <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
<% end %>

        </div>

      </div> 
    <!--- Cada objetivo iterado -->


      <% end %>



          <div class="row">
    <div class="col-xs-12">
    
    <% if current_usuario.es_docente? %><span data-toggle="tooltip" title="Nueva misión">
        <%= link_to '+', new_mision_objetivo_path(@mision), :class =>"btn btn-success" %></span>
     <% end %>
    </div></div>
</div>

</div>


<% if @objetivos.length==0 %>
<% progreso = 0 %>
<% progresoexc = 0 %>
<% vistos = 0 %>
<% else %>

<% progreso = (100 * nest2 / @objetivos.length) %>
<% progresoexc = (100 * nest3 / @objetivos.length) %>

<% vistos = (100 * nest1 / @objetivos.length) %>
<% end %>
<h1 data-toggle="tooltip" title="Para cumplir la misión, deberás obtener al menos dos estrellas en TODOS los objetivos">Progresos personales</h1>
<div class="row">
<div class="col-xs-12 col-sm-4">
  <div class="panel panel-success">
    <div class="panel-heading">Cumplidos (<i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i>)</div>
    <div class="panel-body"><%= nest2 %>/<%= @objetivos.length %></div>
    <div class="panel-footer">

    <div class="progress"> 
      <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar"
  aria-valuenow="<%= progreso %>" aria-valuemin="0" aria-valuemax="100" style="width:<%= progreso %>%">
    <%= progreso %>% Completado
      </div>
    </div>
    </div>
  </div>
</div>


<div class="col-xs-6 col-sm-4">
  <div class="panel panel-info">
    <div class="panel-heading" data-toggle="tooltip" title="Los objetivos cumplidos con excelencia son todos aquellos en los que obtuviste tres estrellas">Con excelencia (<i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></i><i class="fa fa-star" aria-hidden="true"></i>)</div>
    <div class="panel-body"><%= nest3 %>/<%= @objetivos.length %></div>
    <div class="panel-footer">

    <div class="progress"> 
      <div class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar"
  aria-valuenow="<%= progresoexc %>" aria-valuemin="0" aria-valuemax="100" style="width:<%= progresoexc %>%">
    <%= progresoexc %>% Completado
      </div>
    </div>
    </div>
  </div>
</div>


<div class="col-xs-6 col-sm-4">
  <div class="panel panel-default">
    <div class="panel-heading">Vistos (<i class="fa fa-star" aria-hidden="true"></i>)</div>
    <div class="panel-body"><%= nest1 %>/<%= @objetivos.length %></div>
    <div class="panel-footer">

    <div class="progress"> 
      <div class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar"
  aria-valuenow="<%= vistos %>" aria-valuemin="0" aria-valuemax="100" style="width:<%= vistos %>%">
    <%= vistos %>% Completado
      </div>
    </div>
    </div>
  </div>
</div>


</div>




</div>

 <script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip(); 
});
</script>