config/routes.rb
Rails.application.routes.draw do
 
  resources :tableros
  patch 'grupos/agregarusuario', to: 'grupos#agregarusuario'
  put 'grupos/agregarusuario', to: 'grupos#agregarusuario'
  
  resources :grupos do
    resources :posts
  end

  devise_for :usuarios
  get 'misions/mismisiones'

  get 'estrellas/nueva' #Habilitar sólo para pruebas
  post 'estrellas', to: 'estrellas#crear'
  post 'autoes', to: 'estrellas#crearauto'

  get 'usuarios', to: 'usuarios#index'
  get 'usuarios/:idusuario', to: 'usuarios#mostrar', as:'veruser'
  
  patch 'usuarios/darestrellas', to: 'estrellas#darestrellas'
  put 'usuarios/darestrellas', to: 'estrellas#darestrellas'
  




  resources :misions do
  	resources :objetivos
  	member do
  		put "like", to: "misions#upvote"
  		put "dislike", to: "misions#downvote"
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'root#index'
end

app/views/partials/_menu.html.erb
 <div id="container-fluid"> <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
        para mostrarlos mejor en los dispositivos móviles -->
  
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-ex1-collapse ">
      <span class="sr-only">Desplegar navegación</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to("Ludere", misions_path, :class => "navbar-brand") %>

  </div>
 
  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
   

    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-tasks" aria-hidden="true"></i></span> Misiones<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">
            <!---
            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Buscar">
              </div>
              <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            </form> -->


          </a></li>
          <li><a href="/misions/">Explorar misiones</a></li>
          <li class="divider"></li>
          <li><a href="/misions/mismisiones">Mis misiones</a></li>
          <li class="divider"></li>
          <li><a href="#">Misiones de mis grupos</a></li>
        </ul>
      </li>



      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-users" aria-hidden="true"></i> Grupos<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">
            <!---
            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Buscar">
              </div>
              <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            </form> -->


          </a></li>
          <li><%= link_to "Mis grupos", grupos_path %></li>
          <li><%= link_to "Crear nuevo grupo", new_grupo_path %></li>
          <li class="divider"></li>
          <!-- Hacer un bucle y repetir la siguiente línea con cada uno de los grupos del usuario -->
          <li><a href="#">Mi grupo 1</a></li>
        
        </ul>
      </li>



      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-trophy" aria-hidden="true"></i> Logros <span class="badge">5</span><b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Logros globales</a></li>
          <li><a href="#">Logros de mis grupos <span class="badge">3</span></a></li>
          <li class="divider"></li>
          <li><a href="#">Mis logros<span class="badge"> 2</span></a></li>
          <li><a href="#"></a></li>
        </ul>
      </li>
    </ul>
 
   <!-- Iniciar sesión o mostrar menú de navegación privado -->
    <ul class="nav navbar-nav navbar-right" style="padding-right:10px">
      <li class="dropdown">
      <% if usuario_signed_in? %>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i> Menú<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#"><i class="fa fa-inbox" aria-hidden="true"></i> Bandeja de entrada <span class="badge">3</span></a></li>
          <li><a href="#"><i class="fa fa-envelope-o" aria-hidden="true"></i> Nuevo mensaje</a></li>
          <li class="divider"></li>
          <li><a href="#"><i class="fa fa-shield" aria-hidden="true"></i> Tutores</a></li>
          <li class="divider"></li>
          <li><%= link_to content_tag(:i, " ", class: "fa fa-user")+" Perfil", edit_usuario_registration_path %></li>
          <li><%= link_to content_tag(:i, " ", class: "fa fa-times-circle")+" Cerrar sesión", destroy_usuario_session_path, method: :delete %></li>
        </ul>
      <% else %>
          <%= link_to content_tag(:i, " ", class: "fa fa-user")+ " Entrar", new_usuario_session_path %>

         <% end %>


      </li>
    </ul>
  </div>
</nav></div>