config/routes.rb
Rails.application.routes.draw do
 
  resources :tableros
  patch 'grupos/agregarusuario', to: 'grupos#agregarusuario'
  put 'grupos/agregarusuario', to: 'grupos#agregarusuario'
  
  resources :grupos do
    resources :posts
  end

  devise_for :usuarios
  get 'misions/mismisiones'

  get 'estrellas/nueva' #Habilitar sólo para pruebas
  post 'estrellas', to: 'estrellas#crear'
  post 'autoes', to: 'estrellas#crearauto'

  get 'usuarios', to: 'usuarios#index'
  get 'usuarios/:idusuario', to: 'usuarios#mostrar', as:'veruser'
  
  patch 'usuarios/darestrellas', to: 'estrellas#darestrellas'
  put 'usuarios/darestrellas', to: 'estrellas#darestrellas'
  




  resources :misions do
  	resources :objetivos
  	member do
  		put "like", to: "misions#upvote"
  		put "dislike", to: "misions#downvote"
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'root#index'
end

app/models/grupo.rb
class Grupo < ApplicationRecord
	has_many :posts
	has_many :usuarios
	has_many :misions

	serialize :integrantes, Array
	serialize :administradores, Array
	serialize :misiones, Array
	serialize :revision, Array

	#Paperclip
	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  before_action :set_grupo, only: [:show, :edit, :update, :destroy]

  before_action :validarusuario
 
  



  # GET /grupos
  # GET /grupos.json
  def index
    @grupos = Grupo.all
    #Requerir id y nombre de usuarios, id y nombre de misiones

    #condición para mostrar: que el usuario pertenezca al grupo


  end

  # GET /grupos/1
  # GET /grupos/1.json
  def show
    set_grupo
    ext_params

      @eslider = false;
      @administradores.each do |a|
        if current_usuario.id == a.id
          @eslider=true;
        end
      end
    #requerir usuarios integrantes (su id, nombre, imagen)

    #requerir posts del grupo
    @post = Post.new
    #requerir misiones del grupo
  end

  # GET /grupos/new
  def new
    @grupo = Grupo.new
    #requerir usuarios
  end

  # GET /grupos/1/edit
  def edit
    #permitir sólo para líderes de grupo
  end

  # POST /grupos
  # POST /grupos.json
  def create
    @grupo = Grupo.new(grupo_params)

    respond_to do |format|
      if @grupo.save
        format.html { redirect_to @grupo, notice: 'Grupo was successfully created.' }
        format.json { render :show, status: :created, location: @grupo }
      else
        format.html { render :new }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupos/1
  # PATCH/PUT /grupos/1.json
  def update
    respond_to do |format|
      if @grupo.update(grupo_params)
        format.html { redirect_to @grupo, notice: 'Grupo was successfully updated.' }
        format.json { render :show, status: :ok, location: @grupo }
      else
        format.html { render :edit }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  def agregarusuario
    #En @grupo se encuentran los datos del grupo seleccionado.
    @grupo = Grupo.find_by(id: params[:id])


    #Se obtiene el array de integrantes y se incluye el id del usuario al final del mismo
    @grupo.integrantes << current_usuario.id


    #A menos que el grupo sea abierto, se incluirá el id del usuario a la lista de revisión (para que luego sea aceptado por el ĺíder)
    unless @grupo.abierto?
      @grupo.revision << current_usuario.id
    end



    respond_to do |format|
            if @grupo.save
                format.html { redirect_to grupo_path(id: params[:id]), notice: 'Ahora participás del grupo'} #Redireccionar al objetivo
            else
                format.html { redirect_to grupos_path, notice: 'Hubo un error' } #Redireccionar a página de error
            end
          end
  end

  # DELETE /grupos/1
  # DELETE /grupos/1.json
  def destroy
    @grupo.destroy
    respond_to do |format|
      format.html { redirect_to grupos_url, notice: 'Grupo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo
      @grupo = Grupo.find(params[:id])
    end

    def ext_params
      @misiones = Mision.where(id: @grupo.misiones)
      @integrantes = Usuario.where(id: @grupo.integrantes)
      @administradores = Usuario.where(id: @grupo.administradores)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def grupo_params
      params.require(:grupo).permit(:nombre, :descripcion, :integrantes, :misiones, :administradores, :abierto, :image, :revision)
    end
     def validarusuario
      unless usuario_signed_in?
        redirect_to new_usuario_session_path, notice: "Hay que iniciar sesión para acceder a esta sección."
      end
    end 

end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/views/grupos/_form.html.erb
<%= simple_form_for(@grupo) do |f| %>
  <%= f.error_notification %>

 


  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :descripcion %>
   
    <%= f.input :abierto %>
    <%= f.file_field :image %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/grupos/edit.html.erb
<h1>Editing Grupo</h1>

<%= render 'form', grupo: @grupo %>

<%= link_to 'Show', @grupo %> |
<%= link_to 'Back', grupos_path %>

app/views/grupos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grupos </h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Integrantes</th>
      <th>Misiones</th>
      <th>Administradores</th>
      <th>Abierto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupos.each do |grupo| %>
      <tr>
        <td><%= grupo.nombre %></td>
        <td><%= grupo.descripcion %></td>
        <td><%= grupo.integrantes %></td>
        <td><%= grupo.misiones %></td>
        <td><%= grupo.administradores %></td>
        <td><%= grupo.abierto %></td>
        <td><%= link_to 'Show', grupo %></td>
        <td><%= link_to 'Edit', edit_grupo_path(grupo) %></td>
        <td><%= link_to 'Destroy', grupo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grupo', new_grupo_path %>


<div class="transitions-enabled clearfix masonry" >

<% if current_usuario.es_docente? %>
    <div class="box col1 masonry-brick">
    <div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Crear nuevo grupo</h2>
    </div>
   <div class="panel-body">
    <%= link_to '+', new_grupo_path, :class =>"btn btn-success" %>
   </div>
   </div></div>

<% end %>




    <% @grupos.each do |grupo| %>
<div class="box col3 masonry-brick">
    <div class="panel panel-default"> <!-- Agregar distinción de col* según cantidad de visitas -->
    <div class="panel-heading">
        <h2 class="panel-title"><%= grupo.nombre %></h2>
    </div>
    <div class="panel-body">
<%= image_tag grupo.image.url(:large), :class => "img-rounded" %><br>
<small>Misiones: <i><%= grupo.misiones %></i></small>
<p><%= grupo.descripcion %></p>


  <% esmiembro = false %>
  <% grupo.integrantes.each do |i| %>
   
  <%  if current_usuario.id==i %>
  <%    esmiembro = true %>
  <%  end %>
  <% end %>


<% if esmiembro==true %>
    
    <% if grupo.abierto? %>
       <%= link_to "Ver grupo", grupo, :class => "btn btn-default"  %>
    <% else %>
      <% enrevision = false %>
      <% grupo.revision.each do |r| %>
          <%  if current_usuario.id==r %>
              <%    enrevision = true %>
          <%  end %>
      <% end %>
        
        <% if enrevision==true %>
          "Solicitud enviada"
        <% else %>
          <%= link_to "Ver grupo", grupo, :class => "btn btn-default"  %>
          <%= enrevision %>
        <% end %>

     <% end %>

     <% else %>
<%= link_to "Enviar solicitud de participación", grupos_agregarusuario_path("id"=>grupo.id), :method => :patch, :class => "btn btn-default"  %>
<% end %>

<% if current_usuario.es_docente? %>

  <%= link_to "Editar", edit_grupo_path(grupo), :class => "btn btn-warning"  %>
  <%= link_to "Eliminar", grupo, method: :delete, data: { confirm: "¿Estás seguro que deseás eliminar este grupo?" }, class: "btn btn-danger"  %>

<% end %>




    </div>
    </div>
</div>

    <% end %>


</div>

app/views/grupos/new.html.erb
<h1>New Grupo</h1>

<%= render 'form', grupo: @grupo %>

<%= link_to 'Back', grupos_path %>

app/views/grupos/show.html.erb
<p id="notice"><%= notice %></p>
 <div class="row">
      <div class="col-xs-12">

      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><%= @grupo.nombre %> -  <% if @grupo.abierto? %>
  <strong>Grupo abierto</strong>
  <% else %>
<strong>Grupo cerrado</strong>
<%end %></h2>


        </div>
<div class="panel-body">
<div class="col-xs-12 col-sm-6">
<%= image_tag @grupo.image.url(:large), :class => "img-rounded" %></div>
<div class="col-xs-12 col-sm-6">
   <p>
  <%= @grupo.descripcion %>
</p>       

</div></div></div>
<div class="row"><div class="col-xs-12">

              <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#mi">Eventos</a></li>
                <li><a data-toggle="tab" href="#mu">Muro</a></li>
                <li><a data-toggle="tab" href="#in">Integrantes</a></li>
                <li><a data-toggle="tab" href="#lo">Logros</a></li>
              </ul>

              <div class="tab-content panel">
                <div id="mi" class="tab-pane fade in active">
                    <h3>Misiones</h3>
                    <% @misiones.each do |m| %>
                    <div class="row">
                      <div class="col-xs-3 col-sm-2"><%= image_tag m.image.url(:med), :class => "img-circle img-responsive" %></div>
                      <div class="col-xs-6 col-sm-8"><%= link_to m.nombre, mision_path(m.id), :class => "h2" %><br>
                        <p><%= m.descripcion %></p>
                      </div>
                      <div class="col-xs-3 col-sm-2"><% if @eslider==true %> Quitar <%end%></div>
                    </div>
                    <% end %>
                    <% if @eslider==true %>
                      Agregar misión
                    <% end %>
                    <h3>Eventos</h3>
                </div>
                <div id="mu" class="tab-pane fade">
                  <h3>Muro</h3>
                    <%= render "posts/form"  %>
                  <% @grupo.posts.each do |post| %>
                  <div class="posteo">
                    <%= image_tag post.usuario.image.url(:med), :class => "img-circle img-responsive" %><strong><%= post.usuario.email %></strong> dijo:
                    <p>
                    <%= post.contenido %>
                    </p>
                    Denunciar | Me gusta
                  </div>
                  <% end %>
                  
                </div>
                <div id="in" class="tab-pane fade">
                  <h3>Integrantes</h3>
                    <% @integrantes.each do |i| %>
                    <div class="row">
                      <div class="col-xs-3 col-sm-2"><%= image_tag i.image.url(:med), :class => "img-circle img-responsive" %></div>
                      <div class="col-xs-6 col-sm-8"><%= link_to i.nombre, "logrosdelusuario", :class => "h2" %><br>
                        <p><%= i.nombre %></p>
                      </div>
                      <div class="col-xs-3 col-sm-2"><% @administradores.each do |a| %><% if a.id == i.id %>¡LÍDER! <%end%><%end%></div>
                    </div>
                    <% end %>
                    <% if @eslider==true %>
                      Agregar jugador
                    <% end %>
                </div>
                <div id="lo" class="tab-pane fade">
                  <h3>Logros</h3>
                    <%=   %>
                </div>
              </div>
</div>
</div>