config/routes.rb
Rails.application.routes.draw do
 
  resources :tableros
  patch 'grupos/agregarusuario', to: 'grupos#agregarusuario'
  put 'grupos/agregarusuario', to: 'grupos#agregarusuario'
  
  resources :grupos do
    resources :posts
  end

  devise_for :usuarios
  get 'misions/mismisiones'

  get 'estrellas/nueva' #Habilitar sólo para pruebas
  post 'estrellas', to: 'estrellas#crear'
  post 'autoes', to: 'estrellas#crearauto'

  get 'usuarios', to: 'usuarios#index'
  get 'usuarios/:idusuario', to: 'usuarios#mostrar', as:'veruser'
  
  patch 'usuarios/darestrellas', to: 'estrellas#darestrellas'
  put 'usuarios/darestrellas', to: 'estrellas#darestrellas'
  




  resources :misions do
  	resources :objetivos
  	member do
  		put "like", to: "misions#upvote"
  		put "dislike", to: "misions#downvote"
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'root#index'
end

app/models/objetivo.rb
class Objetivo < ApplicationRecord
	belongs_to :mision
end

app/controllers/objetivos_controller.rb
class ObjetivosController < ApplicationController
  before_action :set_objetivo, only: [:show, :edit, :update, :destroy]
  before_action :set_mision  # GET /objetivos
  before_action :validarusuario
  before_action :validaradmin, except: [:show]


  # GET /objetivos.json
  def index
    @objetivos = Objetivo.all
  end

  # GET /objetivos/1
  # GET /objetivos/1.json
  def show
    #@estrellas = Estrella.select("idobjetivo_id", "idusuario_id", "est1", "est2", "est3").where
    @estrella = Estrella.find_by(idusuario_id: current_usuario.id, idobjetivo_id: params[:id])
    
  end

  # GET /objetivos/new
  def new
    @objetivo = Objetivo.new
  end

  # GET /objetivos/1/edit
  def edit
  end

  # POST /objetivos
  # POST /objetivos.json
  def create
    @objetivo = Objetivo.new(objetivo_params)
    @objetivo.mision= @mision

    respond_to do |format|
      if @objetivo.save
        format.html { redirect_to [@mision, @objetivo], notice: 'Objetivo was successfully created.' }
        format.json { render :show, status: :created, location: [@mision, @objetivo] }
      else
        format.html { render :new }
        format.json { render json: [@mision, @objetivo].errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objetivos/1
  # PATCH/PUT /objetivos/1.json
  def update
    respond_to do |format|
      if @objetivo.update(objetivo_params)
        format.html { redirect_to [@mision, @objetivo], notice: 'Objetivo was successfully updated.' }
        format.json { render :show, status: :ok, location: [@mision, @objetivo] }
      else
        format.html { render :edit }
        format.json { render json: [@mision, @objetivo].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objetivos/1
  # DELETE /objetivos/1.json
  def destroy
    @objetivo.destroy
    respond_to do |format|
      format.html { redirect_to mision_objetivos_url, notice: 'Objetivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_mision
    @mision = Mision.find(params[:mision_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_objetivo
      @objetivo = Objetivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objetivo_params
      params.require(:objetivo).permit(:mision_id, :nombre, :descripcion, :urlvideo, :instructivo, :urlevaluativo)
    end
    def mision_params
      params.require(:mision).permit(:id, :nombre)
    end
    def validarusuario
      unless usuario_signed_in?
        redirect_to new_usuario_session_path, notice: "Hay que iniciar sesión para acceder a esta sección."
      end
    end 
    def validaradmin
      unless current_usuario.es_admin?
        redirect_to misions_path, notice: "No disponés de permisos suficientes para acceder a esta sección."
      end
    end
end

app/views/objetivos/_form.html.erb
<%= form_for([@mision, objetivo]) do |f| %>
  <% if objetivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(objetivo.errors.count, "error") %> prohibited this objetivo from being saved:</h2>

      <ul>
      <% objetivo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="input-group">
   <span class="input-group-addon">Nombre del objetivo</span> 
    <%= f.text_field :nombre, :class => "form-control " %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">Descripción</span>
    <%= f.text_field :descripcion, :class => "form-control " %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">URL del video</span>
    <%= f.text_field :urlvideo, :class => "form-control " %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">Instructivo</span>
    <%= f.text_area :instructivo, :class => "form-control " %>
  </div>

  <div class="input-group">
   <span class="input-group-addon">URL de evaluación</span>
    <%= f.text_field :urlevaluativo, :class => "form-control " %>
  </div>

  <div class="actions">
    <%= f.submit "Crear", :class => "btn btn-primary"%>
  </div>

<% end %>

app/views/objetivos/edit.html.erb
<h1>Editing Objetivo</h1>

<%= render 'form', objetivo: @objetivo %>

app/views/objetivos/index.html.erb
SÓLO VISIBLE PARA ADMINISTRADORES
<h1>Objetivos</h1>

<table>
  <thead>
    <tr>
      <th>Mision</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Urlvideo</th>
      <th>Instructivo</th>
      <th>Urlevaluativo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @objetivos.each do |objetivo| %>
      <tr>
        <td><%= objetivo.mision_id %></td>
        <td><%= objetivo.nombre %></td>
        <td><%= objetivo.descripcion %></td>
        <td><%= objetivo.urlvideo %></td>
        <td><%= objetivo.instructivo %></td>
        <td><%= objetivo.urlevaluativo %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo OBJETIVO para esta misión', new_mision_objetivo_path %>

app/views/objetivos/new.html.erb
<h1>Nuevo Objetivo</h1>

<%= render 'form', objetivo: @objetivo %>

app/views/objetivos/show.html.erb
<div class="row">
<div class="col-md-9 col-xs-12">
<div class="panel panel-primary">
  <div class="panel-heading">
    <strong>Objetivo:</strong> <%= @objetivo.nombre %>
  </div>
  <div class="panel-body">
      <strong>Misión:</strong> <%= link_to @mision.nombre, "../" %>
      <p>
        <%= @objetivo.descripcion %>
      </p>
  </div>

</div>


</div>
<div class="col-md-3 col-xs-12">

<div class="panel panel-default">
<div class="panel-heading">Estado del objetivo</div>
<% if @estrella==nil %>
      <i class="fa fa-star-o fa-2x" aria-hidden="true" data-toggle="tooltip" title="¡Primer estrella! Se te otorga cuando viste el video completo"></i>
      <i class="fa fa-star-o fa-2x" aria-hidden="true" data-toggle="tooltip" title="¡Segunda estrella!"></i>
      <i class="fa fa-star-o fa-2x" aria-hidden="true" data-toggle="tooltip" title="¡Tercera estrella!"></i>


<% else %>

        <% if @estrella.est1? %>
       
            <i class="fa fa-star fa-2x" aria-hidden="true" data-toggle="tooltip" title="¡Primer estrella! Se te otorga cuando viste el video completo"></i>
        <%else%>
            <i class="fa fa-star-o fa-2x" aria-hidden="true" data-toggle="tooltip" title="¡Primer estrella! Se te otorga cuando viste el video completo"></i>
        <%end%>

        <% if @estrella.est2? %>
       
            <i class="fa fa-star fa-2x" aria-hidden="true" data-toggle="tooltip" title="¡Segunda estrella!"></i>
        <%else%>
            <i class="fa fa-star-o fa-2x" aria-hidden="true" data-toggle="tooltip" title="¡Segunda estrella!"></i>
        <%end%>

          <% if @estrella.est3? %>
       
            <i class="fa fa-star fa-2x" aria-hidden="true" data-toggle="tooltip" title="¡Tercera estrella!"></i>
        <%else%>
            <i class="fa fa-star-o fa-2x" aria-hidden="true" data-toggle="tooltip" title="¡Tercera estrella!"></i>
        <%end%> 

<% end %>
</div>
</div>



</div>
<div class="row"><div class="col-xs-12">

    <script>
     // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          height: '360',
          width: '640',
          videoId: '<%= @objetivo.urlvideo %>',
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.playVideo();
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.ENDED && !done) {
          // EVENTO PARA MOSTRAR EL TAG OCULTO 
          done = true;
          document.getElementById('seter').style.display = 'block';
        }
      }
      function stopVideo() {
        player.stopVideo();
      }
</script>


  <div class="hs-responsive-embed-youtube"> <div id="player"></div> </div>
  </div><!--- Evento para que cuando termine el video, compruebe que a menos que el usuario ya tenga est1, mande por POST la nueva estrella 1 con el idobjetivo y el idusuario -->



</div>
  <% if @estrella==nil %>
    <div class="row"><div id='seter' style='display:none;'>
    <% e1={"idobjetivo_id"=>@objetivo.id, "mision_id"=>@mision.id}  %>
    <%= link_to "Reclamar primera estrella en el objetivo", autoes_path(e1), :method => :create %><br>
    <i class="fa fa-star fa-3x" aria-hidden="true" data-toggle="tooltip" title="¡Obtener estrella!"></i>
    </div></div>
  <% end %>
<div class="row">
<div class="row"><div class="col-xs-12">

              <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#ay">Ayudas del objetivo</a></li>
                <li><a data-toggle="tab" href="#pr">¡Quiero ver la prueba!</a></li>
              </ul>

              <div class="tab-content panel">
                <div id="ay" class="tab-pane fade in active">
                  <h3>Ayudas</h3>
                    <%= raw @objetivo.instructivo %>
                </div>
                <div id="pr" class="tab-pane fade">
                  <h3>Prueba</h3>
                    <%= link_to "Ir a la prueba", @objetivo.urlevaluativo, target: :_blank  %>
                </div>
              </div>
</div>
</div>

<!--- Sólo para admins
<%= link_to 'Edit', edit_mision_objetivo_path(@objetivo) %> |
<%= link_to 'Back', mision_objetivos_path %> -->